### ISSUE TITLE
HTTP 500 error on fresh non-Docker install (nginx/php7.1-fpm/mysql, ran composer)

### ISSUE THREAD

**Issue by DeusMaximus** [lansuite/lansuite#269] opened 2018-05-16 05:09 UTC
When attempting to run a fresh install on a non-Docker install, I'm greeted by a HTTP 500 error, with the following lines in /var/log/nginx/error.log:

    2018/05/16 14:28:12 [error] 58232#58232: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  
    Uncaught Error: Class 'LanSuite\xml' not found in /usr/share/lansuite/inc/Classes/Translation.php:366
    Stack trace:
    #0 /usr/share/lansuite/inc/Classes/Translation.php(166): LanSuite\Translation->xml_read_to_array('System')
    #1 /usr/share/lansuite/inc/Classes/Translation.php(85): LanSuite\Translation->load_cache_byfile('System')
    #2 /usr/share/lansuite/index.php(276): LanSuite\Translation->load_trans('xml', 'install')
    #3 {main}
    thrown in /usr/share/lansuite/inc/Classes/Translation.php on line 366" while reading response header from upstream, client: x.x.x.x, server: xxxx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "x.x.x.x"

This is running on nginx, php7.1-fpm and mysql, after running composer install in the lansuite directory.

nginx config was copied from the .docker folder, but modified to use unix:/run/php/php7.1-fpm.sock instead of php:9000, and root set to /usr/share/lansuite (the location where I git cloned to).

Setup is on an Ubuntu 16.04.4 LTS minimal server, using ppa:ondrej/php for php7.1-fpm, composer 1.6.2 and latest version of mysql (8.0) from Oracle's repository.

**Comment by andygrunwald** [comment] 2018-05-16 05:53
Hey @DeusMaximus,

I prepared a fix in #270.
Right now we are changing quite a log in the internals of the system. This was one of the causes of the refactoring.
Do you want to test #270 ?

**Comment by DeusMaximus** [comment] 2018-05-16 08:35
Okay, it still persisted until I modified line 253 as well as line 366 in your commit.

The first two pages of the installer seem to work, and then fails again on the third page with another HTTP 500.

Here's the error.log from nginx.

    2018/05/16 18:20:54 [error] 58831#58831: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_tag_content_array() on null in /usr/share/lansuite/modules/install/Classes/Install.php:898
    Stack trace:
    #0 /usr/share/lansuite/modules/install/Classes/Install.php(102): LanSuite\Module\Install\Install->DeleteAllTables()
    #1 /usr/share/lansuite/modules/install/wizard.php(167): LanSuite\Module\Install\Install->TryCreateDB('1')
    #2 /usr/share/lansuite/index_module.inc.php(55): include_once('/usr/share/lans...')
    #3 /usr/share/lansuite/index.php(420): include_once('/usr/share/lans...')
    #4 {main}
    thrown in /usr/share/lansuite/modules/install/Classes/Install.php on line 898" while reading response header from upstream, client: x.x.x.x, server: localhost, request: "POST /index.php?mod=install&action=wizard&step=3 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/index.php?mod=install&action=wizard&step=2"

I've confirmed that the lansuite database was created, along with all the tables, so I'm pretty sure the mysql side of things is okay.

**Comment by DeusMaximus** [comment] 2018-05-16 09:54
Okay, reran step 2 again without deleting existing tables. It now runs out of memory.

    2018/05/16 18:51:38 [error] 59476#59476: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/lansuite/inc/Classes/DB.php on line 200" while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "x.x.x.x"

Increased PHP memory limit to 512MB

    2018/05/16 19:06:03 [error] 59476#59476: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/lansuite/inc/Classes/Translation.php on line 220" while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /index.php?mod=install&action=wizard&step=3 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "x.x.x.x"

Gave the server 2GB and increased PHP memory limit to 1536MB

    2018/05/16 19:52:33 [error] 1164#1164: *11 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock", host: "x.x.x.x"

**Comment by andygrunwald** [comment] 2018-05-16 10:06
@DeusMaximus Let me have a more detailed look later this day or tomorrow ok?
Can you post your docker setup and how you run your containers (sequence of commands) that i can setup the same env like you?

E.g. a docker-compose file? Or something similar?

**Comment by DeusMaximus** [comment] 2018-05-16 23:51
This isn't running as a docker container, but purely as a fresh install of Ubuntu 16.04.4 LTS server with PHP 7.1, nginx, mysql and composer 1.6.2. I'm doing it this way as I may potentially install it onto shared hosting in the future, where I have limited shell access and certainly no access to docker.

PHP setup:

    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    
    sudo apt-get install php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm php7.1-gd php7.1-snmp

MySQL setup:

    curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
    sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
    sudo apt-get update
    sudo apt-get install mysql-server

nginx setup (just using the one in Ubuntu's repository):

    sudo apt-get install nginx

Composer 1.6.2 installed by placing this into a shell script and executing it:

    curl -s -f -L -o /tmp/installer.php     https://raw.githubusercontent.com/composer/getcomposer.org/b107d959a5924af895807021fcef4ffec5a76aa9/web/installer \
        && php -r " \
        \$signature = '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061'; \
        \$hash = hash('SHA384', file_get_contents('/tmp/installer.php')); \
        if (!hash_equals(\$signature, \$hash)) { \
                unlink('/tmp/installer.php'); \
                echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
                exit(1); \
        }" \
        && php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=1.6.2 \
        && composer --ansi --version --no-interaction \
        && rm -rf /tmp/* /tmp/.htaccess

Contents of /etc/nginx/sites-available/default (also /etc/nginx/sites-enabled/default):

    server {
        listen 80;
        index index.php index.html;
        server_name localhost;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /usr/share/lansuite;
    
        # Deny all hidden files that starts with a '.'
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }
    
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/run/php/php7.1-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

Contents of ./inc/base/config.php

    [lansuite]
    version = "Nightly"
    default_design = "simple"
    chmod_dir = 777
    chmod_file = 666
    debugmode = 0

    [database]
    server = "localhost"
    user = "root"
    passwd = "root password goes here (this isn't the real password)"
    database = "lansuite"
    prefix = "ls_"

**Comment by andygrunwald** [comment] 2018-05-18 06:25
I've applied another fix in #275 which can help with this.
This might not cause the memory allocation issues, but maybe helps also.

**Comment by M4LuZ** [comment] 2018-05-18 11:28
Reopened to let requester confirm correct functionality.
@DeusMaximus could you please give it another try with the changes just merged into the master?

**Comment by andygrunwald** [comment] 2018-06-09 08:06
Hey @DeusMaximus,

any new information? Would be cool if you could retry it. We fixed a couple of bugs/regressions since your last call here. See #322 for more details.
Also our new documentation might be able to help you here: https://lansuite.github.io/lansuite/docs/installation.html

_Side note_: There is no response here since 22 days. I there will be no response until Sunday, 24th June 2018 i will close this ticket.

**Comment by M4LuZ** [comment] 2018-09-06 14:00
its a bit after Sunday, 24th June 2018, so closing this now

**Closed by M4LuZ** 2018-09-06 14:00 UTC
Labels: bug, pending-submitter-response
