### ISSUE TITLE
PHP Warnings always shown

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#448] opened 2019-09-25 17:50 UTC
On several windows, PHP Warnings are been shown. We can not figure out how to turn them off.

The index.php is commented like this:

`// If the debug mode is disabled, we launch the original error handler.
// The original error handler shows PHP Warnings in a typical red box
[...]
// If the debug mode is enabled, we register the Symonfy/Debug component.
// This component shows the error in a nice stack trace.
`

But no matter if I have DebugMode 0 or 1, I always get these warnings:

```
> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/gybralanre.de/httpdocs/ext_inc/templates_c/08a56c46978c04528505802e6a62bae77c42b6aa_0.file.result_case.htm.php on line 105
> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/gybralanre.de/httpdocs/ext_inc/templates_c/08a56c46978c04528505802e6a62bae77c42b6aa_0.file.result_case.htm.php on line 105
> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/gybralanre.de/httpdocs/ext_inc/templates_c/08a56c46978c04528505802e6a62bae77c42b6aa_0.file.result_case.htm.php on line 105
> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/gybralanre.de/httpdocs/ext_inc/templates_c/08a56c46978c04528505802e6a62bae77c42b6aa_0.file.result_case.htm.php on line 105
```

![Errors](https://user-images.githubusercontent.com/17451169/65626318-943fa700-dfcd-11e9-8cc1-fa72a902481a.PNG)

These come on nearly every page and on the newest LanSuite
PHP 7.2.22

Can you advice how we turn these warnings off?

**Comment by M4LuZ** [comment] 2019-10-21 14:00
This looks like a duplicate of issue #386
I would suspect that you copied the default template but did not take over the fix listed there

**Comment by M4LuZ** [comment] 2022-03-29 17:22
Closing as there was no feedback either way for two years

**Closed by M4LuZ** 2022-03-29 17:22 UTC
