### ISSUE TITLE
PayPal Payment causes error

### ISSUE THREAD

**Issue by chlctt** [lansuite/lansuite#445] opened 2019-07-15 20:21 UTC
I have setup lansuite and everything is running quite nicely. So far I haven't recognised any error.

When using PayPal to fullfil the payment, users are forwarded to PayPal correctly, choose their way of payment and initiate the payment. When send back to lansuite users are facing an error, which can be seen below.

The money is taken from the user's account and transfered to the target account, but their is no feedback to lansuite. The payment information is not posted.

I have enabled the debug mode, the output can also be seen below.

## Expected Behavior

When redirected back to the lansuite page, the payment information should be posted to the website.

## Current Behavior

`Fatal error: Uncaught Error: Class 'LanSuite\Module\Guestlist\GuestList' not found in /www/htdocs/xxx/xxx/modules/paypal/executepayment.php:33 Stack trace: #0 /www/htdocs/xxx/xxx/index_module.inc.php(90): include_once() #1 /www/htdocs/xxx/xxx/index.php(437): include_once('/www/htdocs/w00...') #2 {main} thrown in /www/htdocs/w00c5610/lan.nkc-clan.de/modules/paypal/executepayment.php on line 33`

```
(1/1) ClassNotFoundExceptionAttempted to load class "GuestList" from namespace "LanSuite\Module\Guestlist".Did you forget a "use" statement for "LanSuite\Module\GuestList\GuestList"?
--
in executepayment.php line 33
at include_once()in index_module.inc.php line 90
at include_once('/www/htdocs/xxx/xxx/index_module.inc.php')in index.php line 437
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Lansuite 5.0 (current master), PHP 7.2
* Operating System and version: 
* Enabled features:

**Comment by M4LuZ** [comment] 2019-07-17 11:17
Thanks for the bugreport!
The error appears a bit strange as the inclusion path seems to be correct and autoloading seems OK, as other objects from the same namespace are loaded before.
Will need to have a go with a test setup to verify this

**Comment by chilly163** [comment] 2019-07-21 07:52
Hi M4LuZ,

I have changed the part as advised, now there is a new error message. Now tested only on PayPal Sandbox.

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function LanSuite\Module\GuestList\GuestList::__construct(), 0 passed in /www/htdocs/XXX/XXX/modules/paypal/executepayment.php on line 33 and exactly 2 expected in /www/htdocs/XXX/XXX/modules/guestlist/Classes/GuestList.php:21 Stack trace: #0 /www/htdocs/XXX/XXX/modules/paypal/executepayment.php(33): LanSuite\Module\GuestList\GuestList->__construct() #1 /www/htdocs/XXX/XXX/index_module.inc.php(90): include_once('/www/htdocs/w00...') #2 /www/htdocs/XXX/XXX/index.php(437): include_once('/www/htdocs/w00...') #3 {main} thrown in /www/htdocs/XXX/XXX/modules/guestlist/Classes/GuestList.php on line 21`

```
(1/1) FatalThrowableError
Type error: Too few arguments to function LanSuite\Module\GuestList\GuestList::__construct(), 0 passed in /www/htdocs/XXX/XXX/modules/paypal/executepayment.php on line 33 and exactly 2 expected

in GuestList.php line 21
at GuestList->__construct()
in executepayment.php line 33
at include_once('/www/htdocs/XXX/XXX/modules/paypal/executepayment.php')
in index_module.inc.php line 90
at include_once('/www/htdocs/XXX/XXX/index_module.inc.php')
in index.php line 437
```

**Comment by M4LuZ** [comment] 2019-07-23 13:12
OK, constructor was changed for dependency injection and it seems the call here was not changed. 
Should be relatively easy to fix...

**Comment by chilly163** [comment] 2019-07-24 10:29
Unfortunately, I cannot fix this on my own. My PHP knowledge isn't far enough developed. :)

So I will wait for advises or an update.

Thanks so far.

**Comment by M4LuZ** [comment] 2024-05-19 09:27
Closing this as the related functionality has been fixed (years ago) 
Just verified that calls work correctly as intended

**Closed by M4LuZ** 2024-05-19 09:27 UTC
Labels: bug
